### ISSUE TITLE
error [ERROR]: Property 'deriveKey' does not exist on type 'SubtleCrypto' on v0.14.3

### ISSUE THREAD

**Issue by gaboroa14** [denodrivers/postgres#366]
After updating to v0.14.3, my deno app crashed. After looking at logs, I saw this error message:

>2022-01-11T14:14:52.929961+00:00 app[web.1]: error [ERROR]: Property 'deriveKey' does not exist on type 'SubtleCrypto'.
>2022-01-11T14:14:52.929969+00:00 app[web.1]:   const key = await crypto.subtle.deriveKey(
>2022-01-11T14:14:52.929970+00:00 app[web.1]:   ~~~~~~~~~
>2022-01-11T14:14:52.929982+00:00 app[web.1]:     at https://deno.land/x/postgres@v0.14.3/connection/scram.ts

I had to downgrade to v0.14.2 to get my app up and running back again.

**Comment by Soremwar** [comment]
0.14.3 removed a dependency in std/hash by using the WebCrypto API (See #362)

This version requires at least Deno 1.16.0 however, as intidicated here https://github.com/denodrivers/postgres#deno-compatibility
